[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/comparador"
  to = "/comparador.html"
  status = 200

[[redirects]]
  from = "/mattebox"
  to = "/mattebox.html"
  status = 200

[[redirects]]
  from = "/gabo3dprint"
  to = "/gabo3dprint.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
